name: Test Self-Hosted Runner

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "GitHub Actions runner on EC2 is working!"
